language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: oKRacJRkIWaTe4V6QpubggywSHi45mLJwgxXcCe1j8vGEuQMC/fk5zkEoDXCaUjHvDU3V/nnl20J/luao7xEfP3leOSII8RMmdVmp8flvcZENVaiAUlkqAXvP1sVHovsFpKmAFnftA4wiWvV4acC31uIj/bXxsPyWKYhv8jRbnAgG/38tgZxgoPr5PhN3s0aVzQfLQpDlAu/xFHn1GGctbZ1TWeFMZqxe5oCs41nyeQLXRO3ACyqxgspUkMmr+xh9p9EGI0w+ealCs5FuDai0wq1DrGrQyMnCZDKE+NRAeHiuiuUHbZMcMb+H841PLrGM1Sr2D2JWCwZ2t+LJlzwA8uFGDxtXRXoZFGblV/iK6kKySJ/yLT7us3OPvAlDWxXb9jpeg7XlAHq1M2+uRy2ZwJF0kmFFpojSKRLwSZAAWe0wp9TsTLiaTmxgOxryyWjvSi4UAIsDVYoPl3x+HJZHiiApIV11ve6KKOaHRF7dogiEzWeS8NobW8zr24CbbNu3UlB3SKxIvujNeIxKX3qPgGgiNU+KnnG9rKXoVD7nUFkBq+9NwHAIH1ALyfGOm+oK+Z10F8dgZhjyKY/u60B3vH4OHbXbIwrDH8kYh6vNxVIg1Nizex2ubsuGindeJd/fhTwDPzCgDWsCC4VqSHVrp15YjtMoCvhjCBQUBPKo9E=
  app: stark-harbor-67361
  on:
    repo: corck/peepchat-ui
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
